'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Mod } from '@/data/mods';

export default function AddonDetailClient({ mod }: { mod: Mod }) {
  const [activeTab, setActiveTab] = useState<'description' | 'files'>('description');
    
      const filePath = `/files/${mod.fileName}`;

        return (
            <div className="container" style={{ display: 'block' }}>
                  {/* Breadcrumbs */}
                        <nav className="breadcrumbs">
                                <Link href="/">Home</Link> <span>/</span> 
                                        <span style={{ color: '#fff' }}>{mod.title}</span>
                                              </nav>

                                                    {/* Project Header */}
                                                          <div className="project-header">
                                                                  <div className="project-header-img">
                                                                             {mod.image ? (
                                                                                           <img src={`/images/${mod.image}`} alt={mod.title} />
                                                                                                      ) : (
                                                                                                                    <div style={{ width: '100%', height: '100%', background: 'linear-gradient(45deg, #2563eb, #1e40af)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'32px', fontWeight:'bold', color:'white' }}>
                                                                                                                                      {mod.title.charAt(0)}
                                                                                                                                                    </div>
                                                                                                                                                               )}
                                                                                                                                                                       </div>
                                                                                                                                                                               <div className="project-header-info">
                                                                                                                                                                                         <h1>{mod.title}</h1>
                                                                                                                                                                                                   <div className="card-author">By <span>{mod.author}</span></div>
                                                                                                                                                                                                             <div className="categories-tags">
                                                                                                                                                                                                                         {mod.tags.map((tag, index) => (
                                                                                                                                                                                                                                       <span key={index} className="tag">{tag}</span>
                                                                                                                                                                                                                                                   ))}
                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                 {/* TABS MENU (Hapus Comments) */}
                                                                                                                                                                                                                                                                                       <div className="tabs">
                                                                                                                                                                                                                                                                                               <div 
                                                                                                                                                                                                                                                                                                         className={`tab-item ${activeTab === 'description' ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                   onClick={() => setActiveTab('description')}
                                                                                                                                                                                                                                                                                                                           >
                                                                                                                                                                                                                                                                                                                                     Description
                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                     <div 
                                                                                                                                                                                                                                                                                                                                                               className={`tab-item ${activeTab === 'files' ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                         onClick={() => setActiveTab('files')}
                                                                                                                                                                                                                                                                                                                                                                                 >
                                                                                                                                                                                                                                                                                                                                                                                           Files
                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                               {/* KONTEN BERUBAH TERGANTUNG TAB */}
                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                           {/* 1. JIKA TAB DESCRIPTION AKTIF */}
                                                                                                                                                                                                                                                                                                                                                                                                                                 {activeTab === 'description' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="detail-layout">
                                                                                                                                                                                                                                                                                                                                                                                                                                                   {/* Main Description */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div className="detail-main">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="description-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div dangerouslySetInnerHTML={{ __html: mod.fullDescription }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {/* Sidebar (TANPA JUMLAH DOWNLOAD & TANPA TOMBOL DOWNLOAD) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div className="detail-aside">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div className="aside-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div className="aside-title">About Project</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="detail-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="detail-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <span className="detail-label">Updated</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <span>{mod.date}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div className="detail-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <span className="detail-label">License</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <span>Free</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* Jumlah download dihapus sesuai request */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {/* 2. JIKA TAB FILES AKTIF (TAMPILAN KEREN) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {activeTab === 'files' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div className="files-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div className="file-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div className="file-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <h3>{mod.fileName}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="file-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <span>Release Type: <strong>R</strong></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <span>Size: -</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <span>Uploaded: {mod.date}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="file-action">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <a href={filePath} download className="btn-download-cool">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Download File
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <p style={{textAlign:'center', fontSize:'12px', color:'#666', marginTop:'20px'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Enjoy playing with {mod.title}!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }