'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import ModCard from '@/components/ModCard';
import { Mod } from '@/data/mods';
import { categoryList } from '@/data/categories';

export default function MainPage({ mods }: { mods: Mod[] }) {
  const [searchQuery, setSearchQuery] = useState('');
    const [selectedCategory, setSelectedCategory] = useState('all');

      // --- LOGIKA FILTER ---
        const filteredMods = mods.filter((mod) => {
            // 1. Cek Search Text
                const matchesSearch = mod.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                                          mod.summary.toLowerCase().includes(searchQuery.toLowerCase());

                                              // 2. Cek Kategori
                                                  // Jika kategori 'all', loloskan semua.
                                                      // Jika tidak, cek apakah tags mod mengandung ID kategori atau Label kategori
                                                          const matchesCategory = selectedCategory === 'all' 
                                                                ? true 
                                                                      : mod.tags.some(tag => 
                                                                                tag.toLowerCase() === selectedCategory.toLowerCase() || 
                                                                                          tag.toLowerCase().includes(selectedCategory.toLowerCase())
                                                                                                  );

                                                                                                      return matchesSearch && matchesCategory;
                                                                                                        });

                                                                                                          return (
                                                                                                              <>
                                                                                                                    {/* HEADER BERSIH (Hanya Logo & Search) */}
                                                                                                                          <header>
                                                                                                                                  <div className="header-left">
                                                                                                                                            <Link href="/" className="logo">
                                                                                                                                                        <div className="logo-icon">K</div>
                                                                                                                                                                    Kraa<span>Dev</span>
                                                                                                                                                                              </Link>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              
                                                                                                                                                                                                      {/* Search Bar Aktif */}
                                                                                                                                                                                                              <div className="search-bar">
                                                                                                                                                                                                                        <svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor">
                                                                                                                                                                                                                                    <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                                                                                                                                                                                                                                              </svg>
                                                                                                                                                                                                                                                        <input 
                                                                                                                                                                                                                                                                    type="text" 
                                                                                                                                                                                                                                                                                placeholder="Search mods..." 
                                                                                                                                                                                                                                                                                            value={searchQuery}
                                                                                                                                                                                                                                                                                                        onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                  <div className="header-right">
                                                                                                                                                                                                                                                                                                                                            {/* Tombol Login Dihapus */}
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                          </header>

                                                                                                                                                                                                                                                                                                                                                                {/* Hero */}
                                                                                                                                                                                                                                                                                                                                                                      <div className="hero">
                                                                                                                                                                                                                                                                                                                                                                              <h1>Minecraft Bedrock Mods</h1>
                                                                                                                                                                                                                                                                                                                                                                                      <p>Temukan repositori mod terbesar di KraaDev.</p>
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <div className="container">
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                  {/* SIDEBAR DINAMIS DARI data/categories.ts */}
                                                                                                                                                                                                                                                                                                                                                                                                                          <aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="filter-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>Categories</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ul className="category-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {categoryList.map((cat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={cat.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setSelectedCategory(cat.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={selectedCategory === cat.id ? 'active' : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="category-icon">{cat.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {cat.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* MAIN LIST */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="controls-bar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="result-count">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Found {filteredMods.length} results 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {selectedCategory !== 'all' && ` for "${selectedCategory}"`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {filteredMods.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          filteredMods.map((mod) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ModCard key={mod.id} mod={mod} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ textAlign: 'center', padding: '40px', color: '#666' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>No mods found.</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Try changing the filter or search keyword.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>&copy; 2025 KraaDev.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }